version: '3.9'

services:

  proxy:
    image: proxy:latest
    container_name: solaredge-proxy
    build:
      context: .
      dockerfile: proxy/Dockerfile
    networks:
      - common_network
    ports:
      - "3443:443"
    depends_on:
      - grafana
    environment:
      - DOMAIN=${PROXY_DOMAIN}
      - ALT_NAMES=${PROXY_ALT_NAMES}
      - TARGET_PORT=3000
      - TARGET_HOST=grafana
      - SSL_PORT=443

  influxdb:
    image: influxdb:2.6-alpine
    container_name: solaredge-influxdb
    restart: unless-stopped
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influxdb:/mnt:rw
      - influxdb:/var/lib/influxdb2:rw
    networks:
      - common_network
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}

  telegraf:
    image: telegraf:latest
    container_name: solaredge-telegraf
    restart: unless-stopped
    volumes:
      # Mount for telegraf config
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf/telegraf-scrape-full-history.conf:/var/lib/telegraf/telegraf-scrape-full-history.conf:ro
      - ./telegraf/solarEdgeCloudScraper.py:/var/lib/telegraf/solarEdgeCloudScraper.py:ro
    build:
      context: .
      dockerfile: telegraf/Dockerfile
    networks:
      - common_network
    depends_on:
      - influxdb
    environment:
      - SOLAREDGE_SITE_ID=${SOLAREDGE_SITE_ID}
      - SOLAREDGE_INVERTER_SN=${SOLAREDGE_INVERTER_SN}
      - SOLAREDGE_API_KEY=${SOLAREDGE_API_KEY}
      - SOLAREDGE_SITE_USERNAME=${SOLAREDGE_SITE_USERNAME}
      - SOLAREDGE_SITE_PW=${SOLAREDGE_SITE_PW}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - UPDATE_WINDOW_START=05:00:00
      - UPDATE_WINDOW_END=23:00:00
      - UPDATE_INTERVAL=15
      - INFLUXDB_MODBUS_BUCKET=${INFLUXDB_MODBUS_BUCKET}
      - INVERTER_MODBUS_ADDRESS=${INVERTER_MODBUS_ADDRESS}

  grafana:
    image: grafana/grafana-enterprise
    container_name: solaredge-grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:rw
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:rw
    networks:
      - common_network
    depends_on:
      - influxdb
    environment:
      - GF_PATHS_LOGS=/var/log/grafana/
      - GF_LOG_MODE=console file
      - GF_LOG_LEVEL=info
      # To get admin/editor access toggle comment on following 3 lines (GF_SECURITY_ADMIN_USER, GF_SECURITY_ADMIN_PASSWORD, GF_AUTH_DISABLE_LOGIN_FORM)
      # - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      # - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/solaredge-cloud_rev1.json
      - GF_INSTALL_PLUGINS=fetzerch-sunandmoon-datasource
      - TZ=Europe/Warsaw
    ports:
      - 3000:3000
    user: "472:100"

volumes:
  grafana_data:
  influxdb:

networks:
  common_network:
    driver: bridge
