version: '3.9'

services:

  proxy:
    image: proxy:latest
    container_name: solaredge-proxy
    build:
      context: .
      dockerfile: proxy/Dockerfile
    environment:
      DOMAIN: localhost
      TARGET_PORT: 3000
      TARGET_HOST: grafana
      SSL_PORT: 443
    networks:
      - common_network
    ports:
      - "3443:443"
    depends_on:
      - grafana

  influxdb:
    image: influxdb:2.6-alpine
    container_name: solaredge-influxdb
    restart: unless-stopped
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influxdb:/mnt:rw
      - influxdb:/var/lib/influxdb2:rw
    networks:
      - common_network
    ports:
      - "8086:8086"

  telegraf:
    image: telegraf:latest
    container_name: solaredge-telegraf
    restart: unless-stopped
    volumes:
      # Mount for telegraf config
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf/telegraf-scrape-full-history.conf:/var/lib/telegraf/telegraf-scrape-full-history.conf:ro
      - ./telegraf/solarEdgeCloudScraper.py:/var/lib/telegraf/solarEdgeCloudScraper.py:ro
    build:
      context: .
      dockerfile: telegraf/Dockerfile
    networks:
      - common_network
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana-enterprise
    container_name: solaredge-grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:rw
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:rw
    networks:
      - common_network
    depends_on:
      - influxdb

volumes:
  grafana_data:
  influxdb:

networks:
  common_network:
    driver: bridge
